### ISSUE TITLE
Project idea

### ISSUE THREAD

**Issue by Samlewis99** [Samlewis99/EMSC4033--Project#1]
We spoke briefly on Monday about how I could use random forests for this project. I just wanted to get some confirmation and guidance on what key points I need to be focusing on to make this work? 
Am I creating a repository with supporting material (ie markdowns and example data samples), and outline how the module works?
@lmoresi @navidcy

**Comment by navidcy** [comment]
Remind me again: Will you be using an already established package? Is the idea to write down some sort of tutorial for how this will be done using a particular package?

**Comment by Samlewis99** [comment]
Yes, The package random forests from scikit learn. I would like to see how this may be better than the regression I did initially in R.
So yes I suppose I would be writing a tutorial for other people to use this package? I'm not really sure though what we are supposed to be doing in this assignment but it seemed like this would be covering it?

**Comment by Samlewis99** [comment]
There is not much scope for me to build upon this package, as it is very extensive machine learning and beyond my knowledge. I want to use this package for my use case and with my data

**Comment by navidcy** [comment]
@Samlewis99, here are last years project planner and project marking schemes. These will get you an idea of what sort of projects people were going for last year:

https://github.com/ANU-RSES-Education/EMSC-4033-2022/blob/main/ProjectPlanner.md

https://github.com/ANU-RSES-Education/EMSC-4033-2022/blob/main/ProjectMarkingScheme.md

A tutorial about how to use a package fits the project. You should do it in a jupyter notebook and then you actually have code that calls the package and demonstrate its functionality, have some simple or even bit more elaborate examples etc.

If writing a tutorial ends up being much shorter project than 3 weeks then you can have an example/application where you apply the methods on some data of your own and then compare with results from R?

How does this sound?

**Comment by Samlewis99** [comment]
Ok, I will try to work around these guidelines. Cheers

**Comment by navidcy** [comment]
You can leave the issue open or open it again if you wanna discuss more! :)
